// Mocks generated by Mockito 5.4.6 from annotations
// in portfolio_performance_demo/test/portfolio_chart_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:portfolio_performance_demo/generated/portfolio_chart.pbgrpc.dart'
    as _i2;
import 'package:portfolio_performance_demo/screens/portfolio_performance/repository/portfolio_chart_api.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePortfolioChartResponse_0 extends _i1.SmartFake
    implements _i2.PortfolioChartResponse {
  _FakePortfolioChartResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IPortfolioChartApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPortfolioChartApi extends _i1.Mock
    implements _i3.IPortfolioChartApi {
  MockIPortfolioChartApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PortfolioChartResponse> getPortfolioChart({
    String? timespan,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPortfolioChart, [], {#timespan: timespan}),
            returnValue: _i4.Future<_i2.PortfolioChartResponse>.value(
              _FakePortfolioChartResponse_0(
                this,
                Invocation.method(#getPortfolioChart, [], {
                  #timespan: timespan,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.PortfolioChartResponse>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
