// Mocks generated by Mockito 5.4.6 from annotations
// in portfolio_performance_demo/test/screens/portfolio_performance_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:portfolio_performance_demo/screens/portfolio_performance/bloc/bloc/portfolio_overview_bloc.dart'
    as _i5;
import 'package:portfolio_performance_demo/screens/portfolio_performance/bloc/bloc/portfolio_performance_bloc.dart'
    as _i3;
import 'package:portfolio_performance_demo/screens/portfolio_performance/repository/portfolio_chart_repository.dart'
    as _i2;
import 'package:portfolio_performance_demo/screens/portfolio_performance/repository/portfolio_overview_repository.dart'
    as _i4;
import 'package:portfolio_performance_demo/theme/theme_bloc.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIPortfolioChartRepository_0 extends _i1.SmartFake
    implements _i2.IPortfolioChartRepository {
  _FakeIPortfolioChartRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePortfolioPerformanceState_1 extends _i1.SmartFake
    implements _i3.PortfolioPerformanceState {
  _FakePortfolioPerformanceState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPortfolioOverviewRepository_2 extends _i1.SmartFake
    implements _i4.IPortfolioOverviewRepository {
  _FakeIPortfolioOverviewRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePortfolioOverviewState_3 extends _i1.SmartFake
    implements _i5.PortfolioOverviewState {
  _FakePortfolioOverviewState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThemeState_4 extends _i1.SmartFake implements _i6.ThemeState {
  _FakeThemeState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PortfolioPerformanceBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioPerformanceBloc extends _i1.Mock
    implements _i3.PortfolioPerformanceBloc {
  MockPortfolioPerformanceBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IPortfolioChartRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIPortfolioChartRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.IPortfolioChartRepository);

  @override
  _i3.PortfolioPerformanceState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePortfolioPerformanceState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.PortfolioPerformanceState);

  @override
  _i7.Stream<_i3.PortfolioPerformanceState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.PortfolioPerformanceState>.empty(),
          )
          as _i7.Stream<_i3.PortfolioPerformanceState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void add(_i3.PortfolioPerformanceEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.PortfolioPerformanceEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.PortfolioPerformanceState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.PortfolioPerformanceEvent>(
    _i8.EventHandler<E, _i3.PortfolioPerformanceState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<
      _i3.PortfolioPerformanceEvent,
      _i3.PortfolioPerformanceState
    >?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i3.PortfolioPerformanceEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i3.PortfolioPerformanceState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PortfolioOverviewBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioOverviewBloc extends _i1.Mock
    implements _i5.PortfolioOverviewBloc {
  MockPortfolioOverviewBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IPortfolioOverviewRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIPortfolioOverviewRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.IPortfolioOverviewRepository);

  @override
  _i5.PortfolioOverviewState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePortfolioOverviewState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.PortfolioOverviewState);

  @override
  _i7.Stream<_i5.PortfolioOverviewState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.PortfolioOverviewState>.empty(),
          )
          as _i7.Stream<_i5.PortfolioOverviewState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void add(_i5.PortfolioOverviewEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.PortfolioOverviewEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.PortfolioOverviewState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.PortfolioOverviewEvent>(
    _i8.EventHandler<E, _i5.PortfolioOverviewState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i5.PortfolioOverviewEvent, _i5.PortfolioOverviewState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i5.PortfolioOverviewEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i5.PortfolioOverviewState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeBloc extends _i1.Mock implements _i6.ThemeBloc {
  MockThemeBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ThemeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeThemeState_4(this, Invocation.getter(#state)),
          )
          as _i6.ThemeState);

  @override
  _i7.Stream<_i6.ThemeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i6.ThemeState>.empty(),
          )
          as _i7.Stream<_i6.ThemeState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i6.ThemeEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i6.ThemeEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.ThemeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i6.ThemeEvent>(
    _i8.EventHandler<E, _i6.ThemeState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i6.ThemeEvent, _i6.ThemeState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(_i6.ThemeEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i8.Change<_i6.ThemeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
